### ISSUE TITLE
Fetch is not defined

### ISSUE THREAD

**Issue by vastamaki** [nicholascelestin/replicate-js#5]
### Bug description

While using the package in nodejs environments, fetch is not defined. I believe there is an error while importing node-fetch package.

### Steps to reproduce

Just by following examples the error will happen.

### Expected behavior

I should not see error which tells me that fetch is not defined

### Anything else?

Small issue, but prevents usage of this package completely.

**Comment by nicholascelestin** [comment]
Hey there,

In node versions older than 18, there is a dependency on node-fetch. Is it still not working when you npm install node fetch?

-Nick

**Comment by vastamaki** [comment]
Yes, the issue exists even though node-fetch is installed

**Comment by nicholascelestin** [comment]
Thanks, @vastamaki for finding the issue and suggesting a fix! The PR ( #6 ) did fix the issue in node but unfortunately broke things in the browser due to checking the undeclared `process` variable. I've merged in a slightly different fix that should work for both cases  ( #7 ). Let me know if you have any issues.

Sorry about the DOA library. This library needs some proper tests to avoid this type of thing in the future.

**Comment by vastamaki** [comment]
Completely forgot that process doesn't exist in browser by default.. too used for React projects nowadays :sweat_smile: LGTM, closing..
